

about :

  name : "wFileExecutor"
  description : "Experimental. Class to execute a collection of templates with inlined JavaScript code to instantiate it. A collection of templates could be co-dependent in which case FileExecutor deduce dependencies and correct order of templates executions."
  version : "0.3.115"
  enabled : 1
  interpreters :
  - nodejs >= 8.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

# execution :
# 
# scripts :
# test : wtest .run proto/**
# docgen : wdocgen staging
# 
path :

  repository : git+https:///github.com/Wandalen/wFileExecutor.git
  origins :
   - git+https:///github.com/Wandalen/wFileExecutor.git
   - npm:///wfileexecutor
  bugs : https:///github.com/Wandalen/wFileExecutor/issues

step :

  export.proto :
    inherit : module.export
    export : path::export
    tar : 0
    criterion :
      debug : 1
      proto : 1

build :

  proto.export :
    criterion :
      default : 1
      debug : 1
      raw : 1
      proto : 1
      export : 1
      tar : 1
      public : 1
    steps :
      - build::debug.raw
      - step::export.proto

